# Generated by Django 4.2.16 on 2024-10-02 18:05

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('books', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='BorrowModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('request_at', models.DateTimeField(auto_now_add=True)),
                ('borrow_at', models.DateTimeField()),
                ('update_at', models.DateTimeField(auto_now=True)),
                ('return_at', models.DateTimeField()),
                ('status', models.CharField(choices=[('BORROW', 'BORROW'), ('REQUEST', 'REQUEST'), ('CANCEL', 'CANCEL')], default='REQUEST', max_length=7)),
                ('book', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='books.booksmodel')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
